/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

/**
 *
 * @author Aryssa
 */
public class SalesOrderPage extends javax.swing.JPanel {
 MainPage parent;
    /**
     * Creates new form SalesOrderPage1
     */
    public SalesOrderPage() {
        initComponents();
    }
    
    public SalesOrderPage(MainPage parent) {
        initComponents();
        this.parent = parent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSalesOrder = new javax.swing.JLabel();
        btnCreateSales = new javax.swing.JButton();
        btnModifySales = new javax.swing.JButton();
        btnDeleteSales = new javax.swing.JButton();
        btnSearchOrder = new javax.swing.JButton();

        labelSalesOrder.setText("SALES ORDER");

        btnCreateSales.setText("Create Sales");
        btnCreateSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateSalesMouseClicked(evt);
            }
        });
        btnCreateSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSalesActionPerformed(evt);
            }
        });

        btnModifySales.setText("ModifySales");
        btnModifySales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifySalesActionPerformed(evt);
            }
        });

        btnDeleteSales.setText("Delete Sales");

        btnSearchOrder.setText("Search Order");
        btnSearchOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCreateSales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModifySales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnDeleteSales, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(btnSearchOrder))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(labelSalesOrder)))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelSalesOrder)
                .addGap(39, 39, 39)
                .addComponent(btnCreateSales)
                .addGap(18, 18, 18)
                .addComponent(btnModifySales)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteSales)
                .addGap(18, 18, 18)
                .addComponent(btnSearchOrder)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifySalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifySalesActionPerformed
        // TODO add your handling code here:
        parent.changeTab(3);
    }//GEN-LAST:event_btnModifySalesActionPerformed

    private void btnCreateSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateSalesMouseClicked
        // TODO add your handling code here:
        parent.changeTab(1);
        
    }//GEN-LAST:event_btnCreateSalesMouseClicked

    private void btnCreateSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateSalesActionPerformed

    private void btnSearchOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOrderActionPerformed
        // TODO add your handling code here:
        parent.changeTab(3);
    }//GEN-LAST:event_btnSearchOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateSales;
    private javax.swing.JButton btnDeleteSales;
    private javax.swing.JButton btnModifySales;
    private javax.swing.JButton btnSearchOrder;
    private javax.swing.JLabel labelSalesOrder;
    // End of variables declaration//GEN-END:variables
}
