/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;
import Classes.SalesOrder;
import javax.swing.JOptionPane;
/**
 *
 * @author Aryssa
 */
public class CreateSalesOrder1 extends javax.swing.JPanel {
    MainPage parent;
    /**
     * Creates new form CreateSalesOrder1
     */
    private SalesOrder salesOrder;
    
    public CreateSalesOrder1() {
        initComponents();
        //salesOrder = new SalesOrder(OrderID, furnitureID, quantity, total, GeneratedBy, ApprovedBy);
    }
    public CreateSalesOrder1(MainPage parent) {
        initComponents();
        this.parent = parent;
        //salesOrder = new SalesOrder(OrderID, furnitureID, quantity, total, GeneratedBy, ApprovedBy);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcreate = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        lblFurnitureID = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblGeneratedBy = new javax.swing.JLabel();
        lblApprovedBy = new javax.swing.JLabel();
        tfOrderID = new javax.swing.JTextField();
        tfFurnitureID = new javax.swing.JTextField();
        tfQuantity = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        tfGeneratedBy = new javax.swing.JTextField();
        tfApprovedBy = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        lblcreate.setText("CREATE SALES ORDER");

        lblOrderID.setText("ORDER ID");

        lblFurnitureID.setText("FURNITURE ID");

        lblQuantity.setText("QUANTITY");

        lblTotal.setText("TOTAL");

        lblGeneratedBy.setText("GENERATED BY");

        lblApprovedBy.setText("APPROVED BY");

        tfOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrderIDActionPerformed(evt);
            }
        });

        tfFurnitureID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFurnitureIDActionPerformed(evt);
            }
        });

        tfQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantityActionPerformed(evt);
            }
        });

        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });

        tfGeneratedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGeneratedByActionPerformed(evt);
            }
        });

        tfApprovedBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApprovedByActionPerformed(evt);
            }
        });

        btnCreate.setText("CREATE ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQuantity)
                                            .addComponent(lblTotal)
                                            .addComponent(lblGeneratedBy)
                                            .addComponent(lblApprovedBy))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblOrderID)
                                    .addComponent(lblFurnitureID))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tfGeneratedBy, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tfOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfFurnitureID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(lblcreate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(btnCreate)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblcreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID)
                    .addComponent(tfOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFurnitureID)
                    .addComponent(tfFurnitureID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(tfQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeneratedBy)
                    .addComponent(tfGeneratedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApprovedBy)
                    .addComponent(tfApprovedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCreate)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrderIDActionPerformed
     String orderID = tfOrderID.getText();
   
    }//GEN-LAST:event_tfOrderIDActionPerformed

    private void tfFurnitureIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFurnitureIDActionPerformed
        // TODO add your handling code here:
        String furnitureID = tfFurnitureID.getText();
        
    }//GEN-LAST:event_tfFurnitureIDActionPerformed

    private void tfQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantityActionPerformed
        // TODO add your handling code here:
        int quantity = Integer.parseInt(tfQuantity.getText());
    }//GEN-LAST:event_tfQuantityActionPerformed

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
        double total = Double.parseDouble(tfTotal.getText());
    }//GEN-LAST:event_tfTotalActionPerformed

    private void tfGeneratedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGeneratedByActionPerformed
        // TODO add your handling code here:
        String GeneratedBy = tfGeneratedBy.getText();
    }//GEN-LAST:event_tfGeneratedByActionPerformed

    private void tfApprovedByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApprovedByActionPerformed
        // TODO add your handling code here:
        String ApprovedBy = tfApprovedBy.getText();
    }//GEN-LAST:event_tfApprovedByActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String id = tfOrderID.getText();
        String furniture = tfFurnitureID.getText();
        int amount = Integer.parseInt(tfQuantity.getText());
        double ttl = Double.parseDouble(tfTotal.getText());
        String gen = tfGeneratedBy.getText();
        String apr = tfApprovedBy.getText();

    // Create a new SalesOrder instance with the retrieved values
    SalesOrder newSalesOrder = new SalesOrder(id,furniture,amount,ttl,gen,apr);

    // Add the new sales order to the list
    newSalesOrder.createSalesOrder(id, furniture, amount, ttl, gen, apr);
        JOptionPane.showMessageDialog(this, "Sales Order Created!");
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblApprovedBy;
    private javax.swing.JLabel lblFurnitureID;
    private javax.swing.JLabel lblGeneratedBy;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblcreate;
    private javax.swing.JTextField tfApprovedBy;
    private javax.swing.JTextField tfFurnitureID;
    private javax.swing.JTextField tfGeneratedBy;
    private javax.swing.JTextField tfOrderID;
    private javax.swing.JTextField tfQuantity;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables
}
